sudo: false
language: ruby
cache: bundler
rvm: 2.1.7
install: bundle install
script: bundle exec rake site:deploy --trace && htmlproof ../teaching.alexcoman.com-pages/ --disable-external --empty-alt-ignore

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production
